/*

 DSPERADO.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 27

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : Constant per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define dspyBank 0

/* Super Gameboy palette 0 */
#define dspySGBPal0c0 6108
#define dspySGBPal0c1 8935
#define dspySGBPal0c2 6596
#define dspySGBPal0c3 6368

/* Super Gameboy palette 1 */
#define dspySGBPal1c0 6108
#define dspySGBPal1c1 8935
#define dspySGBPal1c2 6596
#define dspySGBPal1c3 6368

/* Super Gameboy palette 2 */
#define dspySGBPal2c0 6108
#define dspySGBPal2c1 8935
#define dspySGBPal2c2 6596
#define dspySGBPal2c3 6368

/* Super Gameboy palette 3 */
#define dspySGBPal3c0 6108
#define dspySGBPal3c1 8935
#define dspySGBPal3c2 6596
#define dspySGBPal3c3 6368

/* Gameboy Color palette 0 */
#define dspyCGBPal0c0 5146
#define dspyCGBPal0c1 607
#define dspyCGBPal0c2 32489
#define dspyCGBPal0c3 6368

/* Gameboy Color palette 1 */
#define dspyCGBPal1c0 6108
#define dspyCGBPal1c1 8935
#define dspyCGBPal1c2 7194
#define dspyCGBPal1c3 6368

/* Gameboy Color palette 2 */
#define dspyCGBPal2c0 6108
#define dspyCGBPal2c1 8935
#define dspyCGBPal2c2 6596
#define dspyCGBPal2c3 6368

/* Gameboy Color palette 3 */
#define dspyCGBPal3c0 6108
#define dspyCGBPal3c1 8935
#define dspyCGBPal3c2 6596
#define dspyCGBPal3c3 6368

/* Gameboy Color palette 4 */
#define dspyCGBPal4c0 6108
#define dspyCGBPal4c1 8935
#define dspyCGBPal4c2 6596
#define dspyCGBPal4c3 6368

/* Gameboy Color palette 5 */
#define dspyCGBPal5c0 6108
#define dspyCGBPal5c1 8935
#define dspyCGBPal5c2 6596
#define dspyCGBPal5c3 6368

/* Gameboy Color palette 6 */
#define dspyCGBPal6c0 6108
#define dspyCGBPal6c1 8935
#define dspyCGBPal6c2 6596
#define dspyCGBPal6c3 6368

/* Gameboy Color palette 7 */
#define dspyCGBPal7c0 6108
#define dspyCGBPal7c1 8935
#define dspyCGBPal7c2 6596
#define dspyCGBPal7c3 6368

/* CGB palette entries. */
#define dspyCGB0 0
#define dspyCGB1 0
#define dspyCGB2 0
#define dspyCGB3 0
#define dspyCGB4 0
#define dspyCGB5 0
#define dspyCGB6 0
#define dspyCGB7 0
#define dspyCGB8 1
#define dspyCGB9 1
#define dspyCGB10 1
#define dspyCGB11 1
#define dspyCGB12 1
#define dspyCGB13 1
#define dspyCGB14 1
#define dspyCGB15 1
#define dspyCGB16 1
#define dspyCGB17 1
#define dspyCGB18 1
#define dspyCGB19 1
#define dspyCGB20 1
#define dspyCGB21 1
#define dspyCGB22 1
#define dspyCGB23 1
#define dspyCGB24 1
#define dspyCGB25 1
#define dspyCGB26 1
#define dspyCGB27 1
/* Start of tile array. */
extern unsigned char dspy[];

/* End of DSPERADO.H */
